'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert(
            {tableName: "Module", schema: "security"},
            [
                {
                    "id": 1,
                    "id_parent": null,
                    "module_name": "general",
                    "type": "group",
                    "classes": "",
                    "icon": "",
                    "code": null,
                    "order": 1,
                    "denomination": "General",
                    "url": "",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 2,
                    "id_parent": null,
                    "module_name": "modules",
                    "type": "group",
                    "classes": "",
                    "icon": "",
                    "code": null,
                    "order": 2,
                    "denomination": "Módulos",
                    "url": "",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 3,
                    "id_parent": null,
                    "module_name": "maintenance",
                    "type": "group",
                    "classes": "",
                    "icon": "",
                    "code": null,
                    "order": 3,
                    "denomination": "Mantenimiento",
                    "url": "",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 4,
                    "id_parent": 1,
                    "module_name": "dashboard",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-airplay",
                    "code": "",
                    "order": 1,
                    "denomination": "Principal",
                    "url": "/",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 5,
                    "id_parent": 2,
                    "module_name": "academic",
                    "type": "collapse",
                    "classes": "",
                    "icon": "feather icon-book",
                    "code": "",
                    "order": 1,
                    "denomination": "Academico",
                    "url": "",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 6,
                    "id_parent": 2,
                    "module_name": "persons",
                    "type": "collapse",
                    "classes": "",
                    "icon": "feather icon-users",
                    "code": "",
                    "order": 2,
                    "denomination": "Personas",
                    "url": "",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 7,
                    "id_parent": 2,
                    "module_name": "accounting",
                    "type": "collapse",
                    "classes": "",
                    "icon": "feather icon-trending-up",
                    "code": "",
                    "order": 3,
                    "denomination": "Contabilidad",
                    "url": "",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 8,
                    "id_parent": 2,
                    "module_name": "setting",
                    "type": "collapse",
                    "classes": "",
                    "icon": "feather icon-settings",
                    "code": "",
                    "order": 4,
                    "denomination": "Configuración",
                    "url": "",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 9,
                    "id_parent": 2,
                    "module_name": "reports",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-file-text",
                    "code": "",
                    "order": 13,
                    "denomination": "Reportes",
                    "url": "/reports",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 10,
                    "id_parent": 3,
                    "module_name": "university",
                    "type": "item",
                    "classes": "",
                    "icon": "feather icon-layers",
                    "code": "",
                    "order": 5,
                    "denomination": "Universidad",
                    "url": "/campus",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 11,
                    "id_parent": 3,
                    "module_name": "master",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-flag",
                    "code": "",
                    "order": 6,
                    "denomination": "Maestras",
                    "url": "/master",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 13,
                    "id_parent": 5,
                    "module_name": "programs",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-bookmark",
                    "code": "",
                    "order": 1,
                    "denomination": "Programas",
                    "url": "/programs",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 14,
                    "id_parent": 5,
                    "module_name": "registration",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-award",
                    "code": "",
                    "order": 2,
                    "denomination": "Matrículas",
                    "url": "/registration",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 15,
                    "id_parent": 5,
                    "module_name": "inscription",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-inbox",
                    "code": "",
                    "order": 3,
                    "denomination": "Inscripciones",
                    "url": "/inscription",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 16,
                    "id_parent": 5,
                    "module_name": "openCourse",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-clock",
                    "code": "",
                    "order": 4,
                    "denomination": "Carga horaria",
                    "url": "/open-course",
                    "state": false,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 17,
                    "id_parent": 8,
                    "module_name": "academicCalendar",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-calendar",
                    "code": "",
                    "order": 5,
                    "denomination": "Calen. Academico",
                    "url": "/setting/academic-calendar",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 18,
                    "id_parent": 6,
                    "module_name": "profile",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-user-check",
                    "code": "",
                    "order": 1,
                    "denomination": "Perfiles",
                    "url": "/profile",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 19,
                    "id_parent": 6,
                    "module_name": "administrative",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-user",
                    "code": "",
                    "order": 2,
                    "denomination": "Administrativos",
                    "url": "/administrative",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 20,
                    "id_parent": 6,
                    "module_name": "teacher",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-user",
                    "code": "",
                    "order": 3,
                    "denomination": "Docentes",
                    "url": "/teacher",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 21,
                    "id_parent": 6,
                    "module_name": "student",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-user",
                    "code": "",
                    "order": 4,
                    "denomination": "Estudiantes",
                    "url": "/student",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 22,
                    "id_parent": 7,
                    "module_name": "payment",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-pocket",
                    "code": "",
                    "order": 1,
                    "denomination": "Pagos",
                    "url": "/payment",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 23,
                    "id_parent": 7,
                    "module_name": "box",
                    "type": "item",
                    "classes": "nav-item",
                    "icon": "feather icon-box",
                    "code": "",
                    "order": 2,
                    "denomination": "Caja",
                    "url": "/box",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 24,
                    "id_parent": 8,
                    "module_name": "roles",
                    "type": "item",
                    "classes": "",
                    "icon": "feather icon-shield",
                    "code": "",
                    "order": 1,
                    "denomination": "Roles",
                    "url": "/setting/roles",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 25,
                    "id_parent": 8,
                    "module_name": "users",
                    "type": "item",
                    "classes": "",
                    "icon": "feather icon-user-check",
                    "code": "",
                    "order": 2,
                    "denomination": "Usuarios",
                    "url": "/setting/users",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 26,
                    "id_parent": 8,
                    "module_name": "module",
                    "type": "item",
                    "classes": "",
                    "icon": "feather icon-grid",
                    "code": "",
                    "order": 3,
                    "denomination": "Modulos",
                    "url": "/setting/module",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                },
                {
                    "id": 27,
                    "id_parent": 8,
                    "module_name": "setting",
                    "type": "item",
                    "classes": "",
                    "icon": "feather icon-settings",
                    "code": "",
                    "order": 4,
                    "denomination": "Configuración",
                    "url": "/setting/setting",
                    "state": true,
                    "created_at": "2020-10-13T07:32:00.000Z",
                    "updated_at": "2020-10-13T07:32:00.000Z",
                    "deleted_at": null
                }
            ]
        )


    },

    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete({tableName: 'Module', schema: 'security'}, null, {});
    },


};
