'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.bulkInsert(
            {tableName: "Course", schema: "programs"},
            [
                {
                    "id": 1,
                    "id_ciclo": 1,
                    "code": "MTOEBA0101",
                    "denomination": "Aspectos Epistémicos y profesionales de la psicopedagogía",
                    "abbreviation": "AEPP",
                    "area": "General ",
                    "order": 1,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": null,
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:14:28.152Z",
                    "updated_at": "2020-09-12T01:14:28.152Z",
                    "deleted_at": null
                },
                {
                    "id": 2,
                    "id_ciclo": 1,
                    "code": "MTOEBA0102",
                    "denomination": "Liderazgo y estrategias educativas",
                    "abbreviation": "LEE",
                    "area": "General",
                    "order": 2,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": null,
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:15:30.398Z",
                    "updated_at": "2020-09-12T01:15:30.398Z",
                    "deleted_at": null
                },
                {
                    "id": 3,
                    "id_ciclo": 1,
                    "code": "MTOECT0103",
                    "denomination": "Neurociencia y pedagogía",
                    "abbreviation": "NP",
                    "area": "Especializado ",
                    "order": 3,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": null,
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:16:11.550Z",
                    "updated_at": "2020-09-12T01:16:11.550Z",
                    "deleted_at": null
                },

                {
                    "id": 4,
                    "id_ciclo": 2,
                    "code": "MTOECT0204",
                    "denomination": "Psicología evolutiva y trastornos del educando",
                    "abbreviation": "PETE",
                    "area": "Especializado",
                    "order": 4,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":2,\"label\":\"Liderazgo y estrategias educativas\",\"order\":2}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:05:10.020Z",
                    "deleted_at": null
                },
                {
                    "id": 5,
                    "id_ciclo": 2,
                    "code": "MTOECT0205",
                    "denomination": "Análisis de la realidad educativa y pedagógica",
                    "abbreviation": "AREP",
                    "area": "Especializado",
                    "order": 5,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":3,\"label\":\"Neurociencia y pedagogía\",\"order\":3}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:05:22.174Z",
                    "deleted_at": null
                },
                {
                    "id": 6,
                    "id_ciclo": 2,
                    "code": "MTOEIN0206",
                    "denomination": "Seminario de investigación Científica I: Elaboración del proyecto.",
                    "abbreviation": "SIC-EPI",
                    "area": "Especifico ",
                    "order": 6,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":1,\"label\":\"Aspectos Epistémicos y profesionales de la psicopedagogía\",\"order\":1}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:05:52.882Z",
                    "deleted_at": null
                },
                {
                    "id": 7,
                    "id_ciclo": 3,
                    "code": "MTOECT0307",
                    "denomination": "Técnicas para el tratamiento Psicopedagógico ",
                    "abbreviation": "TTP",
                    "area": "Especializado",
                    "order": 7,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":4,\"label\":\"Psicología evolutiva y trastornos del educando\",\"order\":4}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:06:05.791Z",
                    "deleted_at": null
                },
                {
                    "id": 8,
                    "id_ciclo": 3,
                    "code": "MTOEBA0308",
                    "denomination": "Estadística Aplicada a la Investigación  ",
                    "abbreviation": "EAI",
                    "area": "General",
                    "order": 8,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":5,\"label\":\"Análisis de la realidad educativa y pedagógica\",\"order\":5}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:06:17.166Z",
                    "deleted_at": null
                },
                {
                    "id": 9,
                    "id_ciclo": 3,
                    "code": "MTOEIN0309",
                    "denomination": "Seminario de Investigación Científica\r\nII: Ejecución del Proyecto\r\n",
                    "abbreviation": "SIC-EPII",
                    "area": "Especifico",
                    "order": 9,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":6,\"label\":\"Seminario de investigación Científica I: Elaboración del proyecto.\",\"order\":6}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:06:40.133Z",
                    "deleted_at": null
                },
                {
                    "id": 10,
                    "id_ciclo": 4,
                    "code": "MTOECT0410",
                    "denomination": "Administración, Evaluación Psicopedagógica y orientación vocacional ",
                    "abbreviation": "AEPOV",
                    "area": "Especializado",
                    "order": 10,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":7,\"label\":\"Técnicas para el tratamiento Psicopedagógico \",\"order\":7}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:06:57.810Z",
                    "deleted_at": null
                },
                {
                    "id": 11,
                    "id_ciclo": 4,
                    "code": "MTOECT0411",
                    "denomination": "Dificultades de aprendizaje, consejo y orientación psicopedagógica ",
                    "abbreviation": "DACOP",
                    "area": "Especializado",
                    "order": 11,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":9,\"label\":\"Seminario de Investigación Científica\\r\\nII: Ejecución del Proyecto\\r\\n\",\"order\":9}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:07:20.846Z",
                    "deleted_at": null
                },
                {
                    "id": 12,
                    "id_ciclo": 4,
                    "code": "MTOEIN0412",
                    "denomination": "Seminario de investigación Científica III: Informe de la Tesis ",
                    "abbreviation": "SIC-EPIII",
                    "area": "Especifico",
                    "order": 12,
                    "credits": 5,
                    "practical_hours": 64,
                    "hours": 48,
                    "requirements": "[{\"value\":9,\"label\":\"Seminario de Investigación Científica\\r\\nII: Ejecución del Proyecto\\r\\n\",\"order\":9}]",
                    "opening": null,
                    "type": "Obligatorio",
                    "state": true,
                    "created_at": "2020-09-12T01:22:17.097Z",
                    "updated_at": "2020-09-12T02:07:38.867Z",
                    "deleted_at": null
                }
            ]
        )


    },

    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete({tableName: 'Course', schema: 'programs'}, null, {});
    },


};
